# Generated by Django 4.1.1 on 2022-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='messages',
            field=models.ManyToManyField(to='msg.messagemodel'),
        ),
    ]
