# Generated by Django 4.1.1 on 2022-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_chatmodel_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='messages',
            field=models.ManyToManyField(blank=True, to='msg.messagemodel'),
        ),
    ]
