# Generated by Django 4.1.1 on 2022-09-25 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msg', '0003_alter_chatmodel_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
