# Generated by Django 4.1.1 on 2022-09-25 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0004_alter_chatmodel_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'ordering': ['-last_message_date']},
        ),
    ]
